FOREBET_LEAGUE_MAP: dict[str, str] = {
    "https://www.forebet.com/en/predictions-europe/uefa-champions-league": "Champions League",
    "https://www.forebet.com/en/predictions-europe/uefa-europa-league": "Europa League",
    "https://www.forebet.com/en/predictions-europe/uefa-europa-conference-league": "Conference League",
    "https://www.forebet.com/en/football-tips-and-predictions-for-england/premier-league": "Premier League",
    "https://www.forebet.com/en/football-tips-and-predictions-for-italy/serie-a": "Serie A",
    "https://www.forebet.com/en/football-tips-and-predictions-for-spain/primera-division": "La Liga",
    "https://www.forebet.com/en/football-tips-and-predictions-for-germany/bundesliga": "Bundesliga",
    "https://www.forebet.com/en/football-tips-and-predictions-for-france/ligue1": "Ligue 1",
    "https://www.forebet.com/en/football-tips-and-predictions-for-belgium/jupiler-pro-league": "Jupiler Pro League",
    "https://www.forebet.com/en/football-tips-and-predictions-for-england/championship": "Championship",
    "https://www.forebet.com/en/football-tips-and-predictions-for-portugal/liga-portugal": "Liga Portugal",
    "https://www.forebet.com/en/football-tips-and-predictions-for-brazil/serie-a": "Serie A Brazil",
    "https://www.forebet.com/en/football-tips-and-predictions-for-usa/mls": "MLS",
    "https://www.forebet.com/en/football-tips-and-predictions-for-netherlands/eredivisie": "Eredivisie",
    "https://www.forebet.com/en/football-tips-and-predictions-for-denmark/superliga": "Superliga Denmark",
    "https://www.forebet.com/en/football-tips-and-predictions-for-poland/ekstraklasa": "Ekstraklasa",
    "https://www.forebet.com/en/football-tips-and-predictions-for-argentina/liga-profesional": "Liga Profesional",
    "https://www.forebet.com/en/football-tips-and-predictions-for-japan/j1-league": "J1 League",
    "https://www.forebet.com/en/football-tips-and-predictions-for-turkey/super-lig": "Super Lig",
    "https://www.forebet.com/en/football-tips-and-predictions-for-sweden/allsvenskan": "Allsvenskan",
    "https://www.forebet.com/en/football-predictions-for-croatia/hnl": "HNL",
    "https://www.forebet.com/en/football-tips-and-predictions-for-mexico/liga-mx": "Liga MX",
    "https://www.forebet.com/en/football-tips-and-predictions-for-spain/segunda-division": "Segunda Division",
    "https://www.forebet.com/en/football-tips-and-predictions-for-norway/eliteserien": "Eliteserien",
    "https://www.forebet.com/en/football-tips-and-predictions-for-austria/bundesliga": "Bundesliga Austria",
    "https://www.forebet.com/en/football-tips-and-predictions-for-switzerland/super-league": "Super League Switzerland",
    "https://www.forebet.com/en/football-tips-and-predictions-for-italy/serie-b": "Serie B",
    "https://www.forebet.com/en/football-tips-and-predictions-for-germany/2-bundesliga": "2. Bundesliga",
    "https://www.forebet.com/en/football-tips-and-predictions-for-france/ligue2": "Ligue 2",
    "https://www.forebet.com/en/football-tips-and-predictions-for-scotland/premiership": "Scottish Premiership",
}