# Web Scraper settings
retry_indicators:
  - "403 Forbidden"

block_indicators:
  - "403 Forbidden"

# Matches filtering settings
num_days_ahead: 3
local_timezone: "Europe/Bucharest"

SKIP_PATTERNS:
  - pattern: "\\bU\\d{2}s?\\b"
    description: "Youth team"
  - pattern: "\\bW\\b"
    description: "Women's team"
  - pattern: "\\bII\\b"
    description: "Reserve team II"
  - pattern: "\\b2\\b"
    description: "Reserve team 2"
  - pattern: "\\bIII\\b"
    description: "Reserve team III"
  - pattern: "\\bB\\b"
    description: "B team"
  - pattern: "\\bC\\b"
    description: "C team"
  - pattern: "\\b(Am)\\b"
    description: "Amateur"
  - pattern: "\\bRes\\b"
    description: "Reserve team"

# Crawler settings
CRAWLER_KEYS:
  scorepredictor:
    class: "ScorePredictorFinder"
    contributes_odds: false
    top_leagues_only: true
  soccervista:
    class: "SoccerVistaFinder_per_league"
    contributes_odds: false
    top_leagues_only: true
  whoscored:
    class: "WhoScoredFinder"
    contributes_odds: false
    top_leagues_only: true
  windrawwin:
    class: "WinDrawWinFinder_per_league"
    contributes_odds: false
    top_leagues_only: true
  forebet:
    class: "ForebetFinder"
    contributes_odds: false
    top_leagues_only: true
  vitibet:
    class: "VitibetFinder"
    contributes_odds: false
    top_leagues_only: true
  predictz:
    class: "PredictzFinder"
    contributes_odds: false
    top_leagues_only: true
  onemillionpredictions:
    class: "OneMillionPredictionsFinder"
    contributes_odds: false
    top_leagues_only: true
  footballbettingtips:
    class: "FootballBettingTipsFinder"
    contributes_odds: false
    top_leagues_only: true
  xgscore:
    class: "xGScoreFinder"
    contributes_odds: false
    top_leagues_only: true
  eaglepredict:
    class: "EaglePredictFinder"
    contributes_odds: false
    top_leagues_only: true
  legitpredict:
    class: "LegitPredictFinder"
    contributes_odds: false
    top_leagues_only: true
  betclan:
    class: "BetClanFinder"
    contributes_odds: false
    top_leagues_only: true
  oddsportal:
    class: "OddsPortalFinder"
    contributes_odds: true
    top_leagues_only: true
  betexplorer:
    class: "BetExplorerFinder"
    contributes_odds: true
    top_leagues_only: true
  footballpredictions:
    class: "FootballPredictionsFinder"
    contributes_odds: false
    top_leagues_only: true

RUNNER_SETS:
  actions:
    - vitibet
    - scorepredictor
    - predictz
    - soccervista
    - windrawwin
    - onemillionpredictions
    - xgscore
    - eaglepredict
    - legitpredict
    - betclan
    - footballpredictions
  local:
    - whoscored
    - footballbettingtips
    - forebet
    # - betexplorer
    - oddsportal
  test:
    - betexplorer

#TEST

MAX_CHUNK_SIZE:
  actions: 100
  local: 1
  all: 1
  test: 1
